version: '3'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: habits
      MARIADB_USER: habits
      MARIADB_PASSWORD: habits
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  web:
    image: php:8.2-apache
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

