version: '3'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: habits
      MARIADB_USER: habits
      MARIADB_PASSWORD: habits
    volumes:
      - db_data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile 
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/html
      - ./db/connection.php:/var/www/html/backend/connection.php
    depends_on:
      - db
    environment:
      DB_SERVER: "db"
      DB_USER: "habits"
      DB_PASS: "habits"
      DB_NAME: "habits"
      DB_PORT: 3306
      
volumes: 
  db_data:

